apiVersion: v1
kind: Service
metadata:
  name: mongodb
  lebels:
    app: mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017

  selector:
    app: mongo
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mongo-pv-claim
spec:
    storageClassName: fast
    accessModes:
    - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: "mongo"
  replicas: 3
  template:
    metadata:
      labels:
        role: mongo
        environment: test
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo
          command:
            - mongod
            - "--replSet"
            - rs0
            - "--bind_ip"
            - 0.0.0.0
            - "--smallfiles"
            - "--noprealloc"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-pv-claim
              mountPath: /data/db
        - name: mongo-sidecar
          image: cvallance/mongo-k8s-sidecar
          env:
            - name: MONGO_SIDECAR_POD_LABELS
              value: "role=mongo,environment=test"
