kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-volume-0
  labels:
    type: local
spec:
  storageClassName: fast
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/mongo_0/"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-volume-1
  labels:
    type: local
spec:
  storageClassName: fast
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/mongo_1/"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-volume-2
  labels:
    type: local
spec:
  storageClassName: fast
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/mongo_2/"
